### ISSUE TITLE
to-do

### ISSUE THREAD

**Issue by RoccoPaolillo** [RoccoPaolillo/IPF_multidim#7]
- [ ] make up dataframe with heart failure
- [ ] check IPF for multiple dimension sociodem + ipertension +  heart failure
- [ ] map GIS - dataset
- [ ] run IPF for each geo unit
- [ ] add dynamic
